/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


public final class TestAPIObject {

  public var id: String?

  public var optionalIntSixtyFour: Int64?

  public var nonOptionalIntSixtyFour: Int64

  public var optionalIntThirtyTwo: Int32?

  public var nonOptionalThirtyTwo: Int32

  public var optionalBool: Bool?

  public var nonOptionalBool: Bool

  public var optionalString: String?

  public var nonOptionalString: String

  public var nestedType: TestAPIObject?

  public var nestedTypesList: TList<TestAPIObject>?


  public init(nonOptionalIntSixtyFour: Int64, nonOptionalThirtyTwo: Int32, nonOptionalBool: Bool, nonOptionalString: String) {
    self.nonOptionalIntSixtyFour = nonOptionalIntSixtyFour
    self.nonOptionalThirtyTwo = nonOptionalThirtyTwo
    self.nonOptionalBool = nonOptionalBool
    self.nonOptionalString = nonOptionalString
  }

  public init(id: String?, optionalIntSixtyFour: Int64?, nonOptionalIntSixtyFour: Int64, optionalIntThirtyTwo: Int32?, nonOptionalThirtyTwo: Int32, optionalBool: Bool?, nonOptionalBool: Bool, optionalString: String?, nonOptionalString: String, nestedType: TestAPIObject?, nestedTypesList: TList<TestAPIObject>?) {
    self.id = id
    self.optionalIntSixtyFour = optionalIntSixtyFour
    self.nonOptionalIntSixtyFour = nonOptionalIntSixtyFour
    self.optionalIntThirtyTwo = optionalIntThirtyTwo
    self.nonOptionalThirtyTwo = nonOptionalThirtyTwo
    self.optionalBool = optionalBool
    self.nonOptionalBool = nonOptionalBool
    self.optionalString = optionalString
    self.nonOptionalString = nonOptionalString
    self.nestedType = nestedType
    self.nestedTypesList = nestedTypesList
  }

}

public protocol TestService {

  /// get test service name
  ///
  /// - Returns: String
  /// - Throws: 
  func getName() throws -> String

  /// get test api objects
  ///
  /// - Parameters:
  ///   - quantity: 
  /// - Returns: TList<TestAPIObject>
  /// - Throws: 
  func getTestAPIObjects(quantity: Int64) throws -> TList<TestAPIObject>

}

open class TestServiceClient : TClient /* , TestService */ {

}

open class TestServiceProcessor /* TestService */ {

  typealias ProcessorHandlerDictionary = [String: (Int32, TProtocol, TProtocol, TestService) throws -> Void]

  public var service: TestService

  public required init(service: TestService) {
    self.service = service
  }

}


